#!/bin/sh

echo "PRE PUSH hook checking for installed 'git-lfs' and make 'git lfs pre-push'"

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }

#
# See https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-pre-push.adoc
# If any of those Git objects are associated with Git LFS objects, those objects will be pushed to the Git LFS API.
#
git lfs pre-push "$@"
